name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  repo_builds: bcgov/quickstart-openshift

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    if: "!github.event.pull_request.head.repo.fork"
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [database, migrations, backend, frontend]
        include:
          - package: database
            triggers: ('database/')
          - package: migrations
            build_context: ./backend/db
            triggers: ('backend/db')
          - package: backend
            triggers: ('backend/')
          - package: frontend
            triggers: ('frontend/')
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v1.3.0
        with:
          build_context: ${{ matrix.build_context }}
          keep_versions: 50
          package: ${{ matrix.package }}
          repository: bcgov/quickstart-openshift
          tag: ${{ github.event.number }}
          tag_fallback: test
          token: ${{ secrets.GITHUB_TOKEN }}
          triggers: ${{ matrix.triggers }}

  deploys:
    name: Deploys
    needs: [builds]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        name: [database, backend, frontend]
        include:
          - name: database
            file: database/openshift.deploy.yml
            overwrite: false
          - name: backend
            file: backend/openshift.deploy.yml
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
            penetration_test: true
            verification_path: /api
          - name: frontend
            file: frontend/openshift.deploy.yml
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
            penetration_test: false
    steps:
      - uses: actions/checkout@v4
      - name: Deploys
        uses: ./
        with:
          file: ${{ matrix.file }}
          name: ${{ matrix.name }}
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: ${{ matrix.overwrite }}
          penetration_test: ${{ matrix.penetration_test }}
          parameters:
            -p ZONE=${{ github.event.number }} -p NAME=${{ github.event.repository.name }}
            -p ORG_NAME=bcgov-nr
            ${{ matrix.parameters }}
          repository: bcgov/quickstart-openshift
          verification_path: ${{ matrix.verification_path }}
