name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  repo_builds: bcgov/quickstart-openshift

jobs:
  deploys:
    name: Deploys
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        name: [database, backend, frontend]
        include:
          - name: database
            file: database/openshift.deploy.yml
            overwrite: false
          - name: backend
            file: backend/openshift.deploy.yml
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
            penetration_test: true
            triggers: ('backend/')
            verification_path: /api
          - name: frontend
            file: frontend/openshift.deploy.yml
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
            penetration_test: true
            triggers: ('frontend/')
    steps:
      - uses: actions/checkout@v4
      - name: Deploys
        uses: ./
        with:
          file: ${{ matrix.file }}
          name: ${{ matrix.name }}
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: ${{ matrix.overwrite }}
          penetration_test: ${{ matrix.penetration_test }}
          penetration_test_token: ${{ secrets.GITHUB_TOKEN }}
          parameters:
            -p ZONE=${{ github.event.number }} -p NAME=${{ github.event.repository.name }}
            -p PROMOTE=${{ env.repo_builds }}/${{ matrix.name }}:test
            ${{ matrix.parameters }}
          repository: ${{ env.repo_builds }}
          verification_path: ${{ matrix.verification_path }}
