name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  repo_builds: bcgov/quickstart-openshift

jobs:
  deploys:
    name: Deploys
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        name: [database, backend, frontend]
        include:
          - name: database
            file: templates/database.yml
            overwrite: false
          - name: backend
            file: templates/backend.yml
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
            penetration_test: true
            verification_path: /api
          - name: frontend
            file: templates/frontend.yml
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
            penetration_test: false
            post_deploy: oc create job "frontend-$(date +%s)" --from=cronjob/${{ github.event.repository.name }}-${{ github.event.number }}-cronjob
    steps:
      - uses: actions/checkout@v4
      - name: Deploys
        uses: ./
        with:
          file: ${{ matrix.file }}
          name: ${{ matrix.name }}
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: ${{ matrix.overwrite }}
          parameters:
            -p ZONE=${{ github.event.number }} -p NAME=${{ github.event.repository.name }}
            ${{ matrix.parameters }}
          penetration_test: ${{ matrix.penetration_test }}
          post_deploy: ${{ matrix.post_deploy }}
          verification_path: ${{ matrix.verification_path }}
