name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds-retags:
    name: Builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [backend, database]
        include:
          - package: backend
            triggers: ('backend/')
          - package: database
            triggers: ('database/')
    steps:
      - uses: actions/checkout@v3
      - uses: bcgov-nr/action-conditional-container-builder@v0.0.2
        with:
          package: ${{ matrix.package }}
          tag: ${{ github.event.number }}
          tag_fallback: test
          repository: bcgov/nr-quickstart-typescript
          token: ${{ secrets.GITHUB_TOKEN }}
          triggers: ${{ matrix.triggers }}

  deploys:
    name: Deploys
    needs:
      - builds-retags
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      matrix:
        name: [backend, database, init]
        include:
          - name: backend
            file: backend/openshift.deploy.yml
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
          - name: database
            file: database/openshift.deploy.yml
            overwrite: false
          - name: init
            file: common/openshift.init.yml
            overwrite: false
    steps:
      - uses: actions/checkout@v3
      - name: Deploys
        uses: ./
        with:
          file: ${{ matrix.file }}
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: ${{ matrix.overwrite }}
          penetration_test: true
          parameters:
            -p ZONE=${{ github.event.number }} -p NAME=${{ github.event.repository.name }}
            -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:${{ github.event.number }}
            ${{ matrix.parameters }}
          repository: bcgov/nr-quickstart-typescript
