name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  repo_builds: bcgov/nr-quickstart-typescript

jobs:
  deploys:
    name: Deploys
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      matrix:
        name: [backend, database, frontend, init]
        include:
          - name: backend
            file: backend/openshift.deploy.yml
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
          - name: database
            file: database/openshift.deploy.yml
            overwrite: false
          - name: frontend
            file: frontend/openshift.deploy.yml
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
          - name: init
            file: common/openshift.init.yml
            overwrite: false
    steps:
      - uses: actions/checkout@v3
      - name: Deploys
        uses: ./
        with:
          file: ${{ matrix.file }}
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: ${{ matrix.overwrite }}
          penetration_test: true
          parameters:
            -p ZONE=${{ github.event.number }} -p NAME=${{ github.event.repository.name }}
            -p PROMOTE=${{ env.repo_builds }}/${{ matrix.name }}:test
            ${{ matrix.parameters }}
          repository: ${{ env.repo_builds }}
